name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  msrv:
    name: Rust 1.85 compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install minimum Rust
        run: rustup toolchain install 1.85 --profile minimal

      - name: Check minimum Rust
        run: cargo +1.85 check --locked --all-targets --all-features

  rust:
    name: Rust
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Security audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt,clippy
          rustup default stable

      - name: Build
        run: cargo build --locked --all-targets --all-features

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy --locked --all-targets --all-features

      - name: Test
        run: cargo test --locked --all-targets --all-features

      - name: Documentation
        run: RUSTDOCFLAGS="-D warnings" cargo doc --locked --no-deps --all-features

      - name: Documentation tests
        run: cargo test --locked --doc --all-features

      - name: Package
        run: cargo package --locked --all-features
